accounts/urls.py
from django.conf.urls import url, include
from accounts.views import ProfileView, SignUpView

urlpatterns = [
    url(r'^',include("django.contrib.auth.urls")),
    url(r'^profile/$',ProfileView.as_view(),name="profile"),
    url(r'^signup/$',SignUpView.as_view(),name="signup"),
]

baseportal/urls.py
from django.conf.urls import url
from baseportal.views import homepageView

urlpatterns = [
    url(r'^$', homepageView, name="home")
]

paper/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from paper import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include("accounts.urls",namespace="accounts")),
    url(r'^paper/', include("papermanager.urls",namespace="papermanager")),
    url(r'^review/', include("paperreviewer.urls",namespace="paperreviewer")),
    url(r'^', include("baseportal.urls",namespace="baseportal")),
]
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baseportal/models.py
from django.db import models
from papermanager.models import Paper

# Create your models here.
class PublishedPaper(models.Model):
    published_date=models.DateTimeField(auto_now_add=True)
    paper=models.OneToOneField(Paper)
    whitePaper=models.FileField(upload_to='uploads/%Y-%m-%d/')
    def author(self):
        return self.paper.author
    def __str__(self):
        return self.paper.name

baseportal/views.py
from django.shortcuts import render
from baseportal.models import PublishedPaper

# Create your views here.
def homepageView(request):
    publishedPapers=PublishedPaper.objects.all()
    context={
        "papers":publishedPapers,
    }
    return render(request, "baseportal/homepage.html", context)

baseportal/templates/baseportal/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>
		{% block pagetitle %}Paper Manager{% endblock %}
	</title>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<style>
		body {
			padding-top: 5rem;
		}
	</style>
	
	<script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
	{% block head %}{% endblock %}
</head>
<body>
	{% include "baseportal/navbar.html" %}
	<div class="container">
		
		{% block content %}
		{% endblock %}
	</div>
	
	<script src="{% static 'popper/popper.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	{% block bodyend %}{% endblock %}
</body>
</html>

baseportal/templates/baseportal/homepage.html
{% extends "baseportal/base.html" %}


{% block content %}
<p>Welcome to our site.</p>
<ul>
	{% for el in papers %}
		<li>
			<a href="{{el.whitePaper.url}}">
				{{el}}
			</a>
		</li>
	{% endfor %}
</ul>
{% endblock %}

baseportal/templates/baseportal/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	<a class="navbar-brand" href="{% url 'baseportal:home' %}">Paper Manager</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<div class="navbar-nav mr-auto">
			<a href="{% url 'baseportal:home' %}" class="nav-item nav-link">Home</a>
		</div>
		
		<div class="navbar-nav">
			{% if user.is_authenticated %}
				<a href="{% url 'accounts:profile' %}" class="nav-item nav-link">{{user.username}}</a>
				<a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Log out</a>
			{% else %}
				<span class="navbar-text">Not Logged in</span>
				<a href="{% url 'accounts:login' %}" class="nav-item nav-link">Log in</a>
				<a href="{% url 'accounts:signup' %}" class="nav-item nav-link">Sign up</a>
			{% endif %}
		</div>
	</div>
</nav>
    